services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: ./docker/php
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  composer:
    container_name: composer
    image: composer:latest
    command: ["composer", "install"]
    depends_on: # Para NGINX
      - php
    volumes:
      - ./:/var/www/html
    restart: always
